### ISSUE TITLE
Left and right gradient support

### ISSUE THREAD

**Issue by abeledovictor** [masonwongcs/react-simple-marquee#31]
Do you have support for left and/or right gradients

Here's a screenshot for reference

<img width="509" alt="Screenshot 2024-05-06 at 12 23 56 PM" src="https://github.com/masonwongcs/react-simple-marquee/assets/18119352/de015658-40aa-4ea1-97f8-f86f8addecfd">

**Comment by masonwongcs** [comment]
Not for now, but I can show you an example of how to archive that using CSS:
```css
.marquee-wrapper {
  mask-image: linear-gradient(to right, #000 80%, transparent);
}
```
